name: Deploy to server

on:
  push:
    branches:
      - master  # O la rama que deseas que dispare la acción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}  # Añadir passphrase aquí
          source: "./"
          target: "/home/ubuntu/geekbank-frontend"

      - name: Run deployment script on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}  # Añadir passphrase aquí
          script: |
            cd /home/ubuntu/geekbank-frontend
            ./deploy.sh  # Ejecutar el script de despliegue
